### ISSUE TITLE
Could you share us with the code for running RMM?

### ISSUE THREAD

**Issue by biuyq** [PaulAlbert31/ReLaB#1]
Hi, Albert
     Excellent work for few-shot leaning and SSL! I have been following your works, such as PL, and "Unsupervised Label Noise Modeling and Loss Correction". To reproduce your result with RMM, could you please share the code under "remixmatch" folder with us? Such as condatfenv.yml and train_RMM.sh.  
    Thanks a lot!

**Comment by PaulAlbert31** [comment]
Hi,
Thanks for the kind words. 
I had not realized that the code for RMM/AND had not been pushed. I uploaded everything now, you should be able to reproduce. Thanks for pointing this out.
