### ISSUE TITLE
IDs of samples at different representative levels

### ISSUE THREAD

**Issue by YUE-FAN** [PaulAlbert31/ReLaB#5]
Thanks for the great work. Maybe I overlooked them, but I didn't find the exact sample ids of CIFAR-10 images for the experiments in table VII. Could you please share them? Thanks :)

**Comment by PaulAlbert31** [comment]
Hello, 
The samples ids can be found in the [main_subset.py](https://github.com/PaulAlbert31/ReLaB/blob/e0bb5cbd1fdaf3d14a750d808077ba4fadf2ebb8/main_subset.py#L250) file. They are ordered from less representative to most representative.
The ones we use are:
Most representative: [4255, 6446, 8580, 11759, 12598, 29349, 29433, 33759, 35345, 38639] at index 7
Less representative: [6695, 14891, 19726, 22715, 23999, 34230, 46511, 47457, 49181, 49397] at index 4
Not representative: [7408, 8148, 9850, 10361, 33949, 36506, 37018, 45044, 46443, 47447] at index 0

By setting the --seed argument to 1, the most representative are selected, for --seed 2 the less representative are selected and for --seed 3 the not representative are selected.

**Comment by YUE-FAN** [comment]
Thanks a lot! Very helpful :)
